

// This file is automatically generated.
// It is not in the generated folder for ease-of-use (no relative paths).
// This file must remain in place relative to the generated scripts (<WebProject>/Scripts/Generated).


/// <reference path="coalesce.dependencies.d.ts" />
/// <reference path="Generated/Ko.AuditMetaData.g.ts" />
/// <reference path="Generated/Ko.ElectricMeterExchange.g.ts" />
/// <reference path="Generated/Ko.ElectricMeterExchangeList.g.ts" />
/// <reference path="Generated/Ko.FieldWork.g.ts" />
/// <reference path="Generated/Ko.GasRetrofit.g.ts" />
/// <reference path="Generated/Ko.GasRetrofitList.g.ts" />
/// <reference path="Generated/Ko.Inspection.g.ts" />
/// <reference path="Generated/Ko.LiveAudit.g.ts" />
/// <reference path="Generated/Ko.LiveAuditList.g.ts" />
/// <reference path="Generated/Ko.PostInstallAudit.g.ts" />
/// <reference path="Generated/Ko.PostInstallAuditList.g.ts" />
